# Generated by Django 2.2.8 on 2020-03-07 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SquirrelItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=30, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('sourse', models.CharField(blank=True, max_length=30, null=True)),
                ('category', models.CharField(blank=True, max_length=30, null=True)),
                ('spider_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'squirrel_item',
                'managed': False,
            },
        ),
    ]
